'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'chunklab-book-parser-'));
// Synthetic source and output only; no real course paths are targets.
fs.mkdirSync(path.join(root, 'ref'));
fs.mkdirSync(path.join(root, 'extra/oral-book'), { recursive: true });
const input = path.join(root, 'ref/英语口语8000句-简版 - 备份.txt');
const output = path.join(root, 'extra/oral-book/book.json');
const lines = Array(3173).fill('');
lines[0] = '第一章 测试';
lines[1] = '1 测试';
lines[3172] = '  all long（ 始终/一直/一贯）  ';
fs.writeFileSync(input, lines.join('\n'));
const run = () => spawnSync(process.execPath, [path.resolve(__dirname, 'book-parse.mjs')], { cwd: root, encoding: 'utf8' });
assert.equal(run().status, 0);
const parsed = JSON.parse(fs.readFileSync(output, 'utf8'));
assert.equal(parsed.length, 1);
assert.equal(parsed[0].en, 'all along');
assert.equal(parsed[0].sourceRaw, lines[3172]);
assert.equal(fs.readFileSync(input, 'utf8'), lines.join('\n'));
const before = fs.readFileSync(output);
lines[3172] = 'Unexpected source（不同内容）';
fs.writeFileSync(input, lines.join('\n'));
const rejected = run();
assert.notEqual(rejected.status, 0);
assert.match(rejected.stderr, /获批修订不匹配/);
assert.deepEqual(fs.readFileSync(output), before, 'rejected source does not replace the previous output');
console.log('book parser: approved correction, exact source retention and fail-closed output passed');
